################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Generated_Code/ADC_0.c \
../Generated_Code/ADC_1.c \
../Generated_Code/AS_BLE.c \
../Generated_Code/AS_PRG.c \
../Generated_Code/ASerialLdd1.c \
../Generated_Code/ASerialLdd2.c \
../Generated_Code/AdcLdd2.c \
../Generated_Code/AdcLdd3.c \
../Generated_Code/BAT_LOW.c \
../Generated_Code/BLE_CONNECTED.c \
../Generated_Code/BLE_Mode.c \
../Generated_Code/BLE_RST.c \
../Generated_Code/BitIoLdd1.c \
../Generated_Code/BitIoLdd10.c \
../Generated_Code/BitIoLdd14.c \
../Generated_Code/BitIoLdd15.c \
../Generated_Code/BitIoLdd16.c \
../Generated_Code/BitIoLdd17.c \
../Generated_Code/BitIoLdd18.c \
../Generated_Code/BitIoLdd19.c \
../Generated_Code/BitIoLdd2.c \
../Generated_Code/BitIoLdd20.c \
../Generated_Code/BitIoLdd21.c \
../Generated_Code/BitIoLdd22.c \
../Generated_Code/BitIoLdd23.c \
../Generated_Code/BitIoLdd24.c \
../Generated_Code/BitIoLdd25.c \
../Generated_Code/BitIoLdd26.c \
../Generated_Code/BitIoLdd27.c \
../Generated_Code/BitIoLdd28.c \
../Generated_Code/BitIoLdd29.c \
../Generated_Code/BitIoLdd3.c \
../Generated_Code/BitIoLdd30.c \
../Generated_Code/BitIoLdd31.c \
../Generated_Code/BitIoLdd32.c \
../Generated_Code/BitIoLdd33.c \
../Generated_Code/BitIoLdd34.c \
../Generated_Code/BitIoLdd35.c \
../Generated_Code/BitIoLdd36.c \
../Generated_Code/BitIoLdd37.c \
../Generated_Code/BitIoLdd38.c \
../Generated_Code/BitIoLdd39.c \
../Generated_Code/BitIoLdd4.c \
../Generated_Code/BitIoLdd40.c \
../Generated_Code/BitIoLdd41.c \
../Generated_Code/BitIoLdd5.c \
../Generated_Code/BitIoLdd6.c \
../Generated_Code/BitIoLdd7.c \
../Generated_Code/BitIoLdd8.c \
../Generated_Code/CHARGE_STATUS.c \
../Generated_Code/CI2C1.c \
../Generated_Code/CLS_BLE.c \
../Generated_Code/CS1.c \
../Generated_Code/Cpu.c \
../Generated_Code/DRV1_EN.c \
../Generated_Code/DRV1_FAULT.c \
../Generated_Code/DRV1_PH.c \
../Generated_Code/DRV1_PMODE.c \
../Generated_Code/DRV2_EN.c \
../Generated_Code/DRV2_FAULT.c \
../Generated_Code/DRV2_PH.c \
../Generated_Code/DRV2_PMODE.c \
../Generated_Code/DacLdd1.c \
../Generated_Code/DacLdd2.c \
../Generated_Code/Distance_INT.c \
../Generated_Code/FC1.c \
../Generated_Code/FreeCntrLdd1.c \
../Generated_Code/GI2C1.c \
../Generated_Code/IMU_INT.c \
../Generated_Code/I_LED_L.c \
../Generated_Code/I_LED_ML.c \
../Generated_Code/I_LED_MR.c \
../Generated_Code/I_LED_R.c \
../Generated_Code/I_LED_SL.c \
../Generated_Code/I_LED_SR.c \
../Generated_Code/I_Motor_L.c \
../Generated_Code/I_Motor_R.c \
../Generated_Code/JOY_DOWN.c \
../Generated_Code/JOY_LEFT.c \
../Generated_Code/JOY_PUSH.c \
../Generated_Code/JOY_RIGHT.c \
../Generated_Code/JOY_UP.c \
../Generated_Code/Kill.c \
../Generated_Code/LED_BLUE_F_L.c \
../Generated_Code/LED_BLUE_F_R.c \
../Generated_Code/LED_GREEN_F_L.c \
../Generated_Code/LED_GREEN_F_R.c \
../Generated_Code/LED_RED_F_L.c \
../Generated_Code/LED_RED_F_R.c \
../Generated_Code/LEDpin1.c \
../Generated_Code/LEDpin2.c \
../Generated_Code/LEDpin3.c \
../Generated_Code/LEDpin4.c \
../Generated_Code/LEDpin5.c \
../Generated_Code/LEDpin6.c \
../Generated_Code/MCUC1.c \
../Generated_Code/PE_LDD.c \
../Generated_Code/PWR_BTN.c \
../Generated_Code/PWR_SW.c \
../Generated_Code/Pins1.c \
../Generated_Code/SLEEP_L.c \
../Generated_Code/SLEEP_R.c \
../Generated_Code/SM1.c \
../Generated_Code/SMasterLdd1.c \
../Generated_Code/SYSOFF.c \
../Generated_Code/TU3.c \
../Generated_Code/TU5.c \
../Generated_Code/TimerIntLdd1.c \
../Generated_Code/UTIL1.c \
../Generated_Code/WAIT1.c \
../Generated_Code/XF1.c 

OBJS += \
./Generated_Code/ADC_0.o \
./Generated_Code/ADC_1.o \
./Generated_Code/AS_BLE.o \
./Generated_Code/AS_PRG.o \
./Generated_Code/ASerialLdd1.o \
./Generated_Code/ASerialLdd2.o \
./Generated_Code/AdcLdd2.o \
./Generated_Code/AdcLdd3.o \
./Generated_Code/BAT_LOW.o \
./Generated_Code/BLE_CONNECTED.o \
./Generated_Code/BLE_Mode.o \
./Generated_Code/BLE_RST.o \
./Generated_Code/BitIoLdd1.o \
./Generated_Code/BitIoLdd10.o \
./Generated_Code/BitIoLdd14.o \
./Generated_Code/BitIoLdd15.o \
./Generated_Code/BitIoLdd16.o \
./Generated_Code/BitIoLdd17.o \
./Generated_Code/BitIoLdd18.o \
./Generated_Code/BitIoLdd19.o \
./Generated_Code/BitIoLdd2.o \
./Generated_Code/BitIoLdd20.o \
./Generated_Code/BitIoLdd21.o \
./Generated_Code/BitIoLdd22.o \
./Generated_Code/BitIoLdd23.o \
./Generated_Code/BitIoLdd24.o \
./Generated_Code/BitIoLdd25.o \
./Generated_Code/BitIoLdd26.o \
./Generated_Code/BitIoLdd27.o \
./Generated_Code/BitIoLdd28.o \
./Generated_Code/BitIoLdd29.o \
./Generated_Code/BitIoLdd3.o \
./Generated_Code/BitIoLdd30.o \
./Generated_Code/BitIoLdd31.o \
./Generated_Code/BitIoLdd32.o \
./Generated_Code/BitIoLdd33.o \
./Generated_Code/BitIoLdd34.o \
./Generated_Code/BitIoLdd35.o \
./Generated_Code/BitIoLdd36.o \
./Generated_Code/BitIoLdd37.o \
./Generated_Code/BitIoLdd38.o \
./Generated_Code/BitIoLdd39.o \
./Generated_Code/BitIoLdd4.o \
./Generated_Code/BitIoLdd40.o \
./Generated_Code/BitIoLdd41.o \
./Generated_Code/BitIoLdd5.o \
./Generated_Code/BitIoLdd6.o \
./Generated_Code/BitIoLdd7.o \
./Generated_Code/BitIoLdd8.o \
./Generated_Code/CHARGE_STATUS.o \
./Generated_Code/CI2C1.o \
./Generated_Code/CLS_BLE.o \
./Generated_Code/CS1.o \
./Generated_Code/Cpu.o \
./Generated_Code/DRV1_EN.o \
./Generated_Code/DRV1_FAULT.o \
./Generated_Code/DRV1_PH.o \
./Generated_Code/DRV1_PMODE.o \
./Generated_Code/DRV2_EN.o \
./Generated_Code/DRV2_FAULT.o \
./Generated_Code/DRV2_PH.o \
./Generated_Code/DRV2_PMODE.o \
./Generated_Code/DacLdd1.o \
./Generated_Code/DacLdd2.o \
./Generated_Code/Distance_INT.o \
./Generated_Code/FC1.o \
./Generated_Code/FreeCntrLdd1.o \
./Generated_Code/GI2C1.o \
./Generated_Code/IMU_INT.o \
./Generated_Code/I_LED_L.o \
./Generated_Code/I_LED_ML.o \
./Generated_Code/I_LED_MR.o \
./Generated_Code/I_LED_R.o \
./Generated_Code/I_LED_SL.o \
./Generated_Code/I_LED_SR.o \
./Generated_Code/I_Motor_L.o \
./Generated_Code/I_Motor_R.o \
./Generated_Code/JOY_DOWN.o \
./Generated_Code/JOY_LEFT.o \
./Generated_Code/JOY_PUSH.o \
./Generated_Code/JOY_RIGHT.o \
./Generated_Code/JOY_UP.o \
./Generated_Code/Kill.o \
./Generated_Code/LED_BLUE_F_L.o \
./Generated_Code/LED_BLUE_F_R.o \
./Generated_Code/LED_GREEN_F_L.o \
./Generated_Code/LED_GREEN_F_R.o \
./Generated_Code/LED_RED_F_L.o \
./Generated_Code/LED_RED_F_R.o \
./Generated_Code/LEDpin1.o \
./Generated_Code/LEDpin2.o \
./Generated_Code/LEDpin3.o \
./Generated_Code/LEDpin4.o \
./Generated_Code/LEDpin5.o \
./Generated_Code/LEDpin6.o \
./Generated_Code/MCUC1.o \
./Generated_Code/PE_LDD.o \
./Generated_Code/PWR_BTN.o \
./Generated_Code/PWR_SW.o \
./Generated_Code/Pins1.o \
./Generated_Code/SLEEP_L.o \
./Generated_Code/SLEEP_R.o \
./Generated_Code/SM1.o \
./Generated_Code/SMasterLdd1.o \
./Generated_Code/SYSOFF.o \
./Generated_Code/TU3.o \
./Generated_Code/TU5.o \
./Generated_Code/TimerIntLdd1.o \
./Generated_Code/UTIL1.o \
./Generated_Code/WAIT1.o \
./Generated_Code/XF1.o 

C_DEPS += \
./Generated_Code/ADC_0.d \
./Generated_Code/ADC_1.d \
./Generated_Code/AS_BLE.d \
./Generated_Code/AS_PRG.d \
./Generated_Code/ASerialLdd1.d \
./Generated_Code/ASerialLdd2.d \
./Generated_Code/AdcLdd2.d \
./Generated_Code/AdcLdd3.d \
./Generated_Code/BAT_LOW.d \
./Generated_Code/BLE_CONNECTED.d \
./Generated_Code/BLE_Mode.d \
./Generated_Code/BLE_RST.d \
./Generated_Code/BitIoLdd1.d \
./Generated_Code/BitIoLdd10.d \
./Generated_Code/BitIoLdd14.d \
./Generated_Code/BitIoLdd15.d \
./Generated_Code/BitIoLdd16.d \
./Generated_Code/BitIoLdd17.d \
./Generated_Code/BitIoLdd18.d \
./Generated_Code/BitIoLdd19.d \
./Generated_Code/BitIoLdd2.d \
./Generated_Code/BitIoLdd20.d \
./Generated_Code/BitIoLdd21.d \
./Generated_Code/BitIoLdd22.d \
./Generated_Code/BitIoLdd23.d \
./Generated_Code/BitIoLdd24.d \
./Generated_Code/BitIoLdd25.d \
./Generated_Code/BitIoLdd26.d \
./Generated_Code/BitIoLdd27.d \
./Generated_Code/BitIoLdd28.d \
./Generated_Code/BitIoLdd29.d \
./Generated_Code/BitIoLdd3.d \
./Generated_Code/BitIoLdd30.d \
./Generated_Code/BitIoLdd31.d \
./Generated_Code/BitIoLdd32.d \
./Generated_Code/BitIoLdd33.d \
./Generated_Code/BitIoLdd34.d \
./Generated_Code/BitIoLdd35.d \
./Generated_Code/BitIoLdd36.d \
./Generated_Code/BitIoLdd37.d \
./Generated_Code/BitIoLdd38.d \
./Generated_Code/BitIoLdd39.d \
./Generated_Code/BitIoLdd4.d \
./Generated_Code/BitIoLdd40.d \
./Generated_Code/BitIoLdd41.d \
./Generated_Code/BitIoLdd5.d \
./Generated_Code/BitIoLdd6.d \
./Generated_Code/BitIoLdd7.d \
./Generated_Code/BitIoLdd8.d \
./Generated_Code/CHARGE_STATUS.d \
./Generated_Code/CI2C1.d \
./Generated_Code/CLS_BLE.d \
./Generated_Code/CS1.d \
./Generated_Code/Cpu.d \
./Generated_Code/DRV1_EN.d \
./Generated_Code/DRV1_FAULT.d \
./Generated_Code/DRV1_PH.d \
./Generated_Code/DRV1_PMODE.d \
./Generated_Code/DRV2_EN.d \
./Generated_Code/DRV2_FAULT.d \
./Generated_Code/DRV2_PH.d \
./Generated_Code/DRV2_PMODE.d \
./Generated_Code/DacLdd1.d \
./Generated_Code/DacLdd2.d \
./Generated_Code/Distance_INT.d \
./Generated_Code/FC1.d \
./Generated_Code/FreeCntrLdd1.d \
./Generated_Code/GI2C1.d \
./Generated_Code/IMU_INT.d \
./Generated_Code/I_LED_L.d \
./Generated_Code/I_LED_ML.d \
./Generated_Code/I_LED_MR.d \
./Generated_Code/I_LED_R.d \
./Generated_Code/I_LED_SL.d \
./Generated_Code/I_LED_SR.d \
./Generated_Code/I_Motor_L.d \
./Generated_Code/I_Motor_R.d \
./Generated_Code/JOY_DOWN.d \
./Generated_Code/JOY_LEFT.d \
./Generated_Code/JOY_PUSH.d \
./Generated_Code/JOY_RIGHT.d \
./Generated_Code/JOY_UP.d \
./Generated_Code/Kill.d \
./Generated_Code/LED_BLUE_F_L.d \
./Generated_Code/LED_BLUE_F_R.d \
./Generated_Code/LED_GREEN_F_L.d \
./Generated_Code/LED_GREEN_F_R.d \
./Generated_Code/LED_RED_F_L.d \
./Generated_Code/LED_RED_F_R.d \
./Generated_Code/LEDpin1.d \
./Generated_Code/LEDpin2.d \
./Generated_Code/LEDpin3.d \
./Generated_Code/LEDpin4.d \
./Generated_Code/LEDpin5.d \
./Generated_Code/LEDpin6.d \
./Generated_Code/MCUC1.d \
./Generated_Code/PE_LDD.d \
./Generated_Code/PWR_BTN.d \
./Generated_Code/PWR_SW.d \
./Generated_Code/Pins1.d \
./Generated_Code/SLEEP_L.d \
./Generated_Code/SLEEP_R.d \
./Generated_Code/SM1.d \
./Generated_Code/SMasterLdd1.d \
./Generated_Code/SYSOFF.d \
./Generated_Code/TU3.d \
./Generated_Code/TU5.d \
./Generated_Code/TimerIntLdd1.d \
./Generated_Code/UTIL1.d \
./Generated_Code/WAIT1.d \
./Generated_Code/XF1.d 


# Each subdirectory must supply rules for building sources it contributes
Generated_Code/%.o: ../Generated_Code/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections  -g3 -DKDS_BUILD=1 -I"C:\Users\Theo\Documents\Fachhochschule\Sem_9\BAT\3_Software\lib\include\DrivingControl" -I"C:\Users\Theo\Documents\Fachhochschule\Sem_9\BAT\3_Software\git\BATMAZEEXPLOR\MCCAR_V_2_75\Static_Code\PDD" -I"C:\Users\Theo\Documents\Fachhochschule\Sem_9\BAT\3_Software\git\BATMAZEEXPLOR\MCCAR_V_2_75\Static_Code\IO_Map" -I"C:\Users\Theo\Documents\Fachhochschule\Sem_9\BAT\3_Software\git\BATMAZEEXPLOR\MCCAR_V_2_75\Sources" -I"C:\Users\Theo\Documents\Fachhochschule\Sem_9\BAT\3_Software\git\BATMAZEEXPLOR\MCCAR_V_2_75\Generated_Code" -I"C:\Users\Theo\Documents\Fachhochschule\Sem_9\BAT\3_Software\git\BATMAZEEXPLOR\MCCAR_V_2_75\Static_Code\System" -I"C:/Users/Theo/Documents/Fachhochschule/Sem_9/BAT/3_Software/git/BATMAZEEXPLOR/MCCAR_V_2_75/Static_Code/System" -I"C:/Users/Theo/Documents/Fachhochschule/Sem_9/BAT/3_Software/git/BATMAZEEXPLOR/MCCAR_V_2_75/Static_Code/PDD" -I"C:/Users/Theo/Documents/Fachhochschule/Sem_9/BAT/3_Software/git/BATMAZEEXPLOR/MCCAR_V_2_75/Static_Code/IO_Map" -I"C:\Freescale\KDS_v3\eclipse\ProcessorExpert/lib/Kinetis/pdd/inc" -I"C:/Users/Theo/Documents/Fachhochschule/Sem_9/BAT/3_Software/git/BATMAZEEXPLOR/MCCAR_V_2_75/Sources" -I"C:/Users/Theo/Documents/Fachhochschule/Sem_9/BAT/3_Software/git/BATMAZEEXPLOR/MCCAR_V_2_75/Generated_Code" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


