/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : CLS_BLE.h
**     Project     : MCCAR_V_2_75
**     Processor   : MK24FN1M0VDC12
**     Component   : Shell
**     Version     : Component 01.106, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-10-01, 16:31, # CodeGen: 192
**     Abstract    :
**         Module implementing a command line shell.
**     Settings    :
**          Component name                                 : CLS_BLE
**          Echo                                           : no
**          Prompt                                         : "CMD> "
**          Project Name                                   : My Project Name
**          Silent Mode Prefix                             : #
**          Buffer Size                                    : 48
**          Blocking Send                                  : Enabled
**            Wait                                         : WAIT1
**            Timeout (ms)                                 : 20
**            Wait Time (ms)                               : 5
**            RTOS Wait                                    : no
**          Status Colon Pos                               : 13
**          Help Semicolon Pos                             : 26
**          Multi Command                                  : Disabled
**          Utility                                        : UTIL1
**          Default Serial                                 : Enabled
**            Console Interface                            : AS_BLE
**          Semaphore                                      : no
**          Critical Section                               : CS1
**          History                                        : no
**          Kinetis SDK                                    : MCUC1
**     Contents    :
**         PrintPrompt                  - void CLS_BLE_PrintPrompt(CLS_BLE_ConstStdIOType *io);
**         SendNum8u                    - void CLS_BLE_SendNum8u(uint8_t val, CLS_BLE_StdIO_OutErr_FctType io);
**         SendNum8s                    - void CLS_BLE_SendNum8s(int8_t val, CLS_BLE_StdIO_OutErr_FctType io);
**         SendNum16u                   - void CLS_BLE_SendNum16u(uint16_t val, CLS_BLE_StdIO_OutErr_FctType io);
**         SendNum16s                   - void CLS_BLE_SendNum16s(int16_t val, CLS_BLE_StdIO_OutErr_FctType io);
**         SendNum32u                   - void CLS_BLE_SendNum32u(uint32_t val, CLS_BLE_StdIO_OutErr_FctType io);
**         SendNum32s                   - void CLS_BLE_SendNum32s(int32_t val, CLS_BLE_StdIO_OutErr_FctType io);
**         SendCh                       - void CLS_BLE_SendCh(uint8_t ch, CLS_BLE_StdIO_OutErr_FctType io);
**         SendStr                      - void CLS_BLE_SendStr(const uint8_t *str, CLS_BLE_StdIO_OutErr_FctType io);
**         PrintMemory                  - uint8_t CLS_BLE_PrintMemory(void *hndl, uint32_t startAddr, uint32_t endAddr,...
**         printfIO                     - unsigned CLS_BLE_printfIO(CLS_BLE_ConstStdIOType *io, const char *fmt, ...);
**         printf                       - unsigned CLS_BLE_printf(const char *fmt, ...);
**         SendData                     - void CLS_BLE_SendData(const uint8_t *data, uint16_t dataSize,...
**         PrintStatus                  - uint8_t CLS_BLE_PrintStatus(CLS_BLE_ConstStdIOType *io);
**         ParseCommand                 - uint8_t CLS_BLE_ParseCommand(const uint8_t *cmd, bool *handled,...
**         IsHistoryCharacter           - bool CLS_BLE_IsHistoryCharacter(uint8_t ch, uint8_t *cmdBuf, size_t...
**         ReadLine                     - bool CLS_BLE_ReadLine(uint8_t *bufStart, uint8_t *buf, size_t bufSize,...
**         PrintCommandFailed           - void CLS_BLE_PrintCommandFailed(const uint8_t *cmd, CLS_BLE_ConstStdIOType *io);
**         IterateTable                 - uint8_t CLS_BLE_IterateTable(const uint8_t *cmd, bool *handled,...
**         SetStdio                     - uint8_t CLS_BLE_SetStdio(CLS_BLE_ConstStdIOTypePtr stdio);
**         GetStdio                     - CLS_BLE_ConstStdIOTypePtr CLS_BLE_GetStdio(void);
**         RequestSerial                - void CLS_BLE_RequestSerial(void);
**         ReleaseSerial                - void CLS_BLE_ReleaseSerial(void);
**         ReadAndParseWithCommandTable - uint8_t CLS_BLE_ReadAndParseWithCommandTable(uint8_t *cmdBuf, size_t...
**         ParseWithCommandTable        - uint8_t CLS_BLE_ParseWithCommandTable(const uint8_t *cmd,...
**         GetSemaphore                 - void* CLS_BLE_GetSemaphore(void);
**         SendStatusStr                - void CLS_BLE_SendStatusStr(const uint8_t *strItem, const uint8_t *strStatus,...
**         SendHelpStr                  - void CLS_BLE_SendHelpStr(const uint8_t *strCmd, const uint8_t *strHelp,...
**         ReadChar                     - void CLS_BLE_ReadChar(uint8_t *c);
**         SendChar                     - void CLS_BLE_SendChar(uint8_t ch);
**         KeyPressed                   - bool CLS_BLE_KeyPressed(void);
**         SendCharFct                  - void CLS_BLE_SendCharFct(uint8_t ch, uint8_t (*fct)(uint8_t ch));
**         Init                         - void CLS_BLE_Init(void);
**         Deinit                       - void CLS_BLE_Deinit(void);
**
**Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**All Rights Reserved.
**
**Redistribution and use in source and binary forms, with or without modification,
**are permitted provided that the following conditions are met:
**
**o Redistributions of source code must retain the above copyright notice, this list
**  of conditions and the following disclaimer.
**
**o Redistributions in binary form must reproduce the above copyright notice, this
**  list of conditions and the following disclaimer in the documentation and/or
**  other materials provided with the distribution.
**
**o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**  contributors may be used to endorse or promote products derived from this
**  software without specific prior written permission.
**
**THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**http: www.freescale.com
**mail: support@freescale.com
** ###################################################################*/
/*!
** @file CLS_BLE.h
** @version 01.00
** @brief
**         Module implementing a command line shell.
*/         
/*!
**  @addtogroup CLS_BLE_module CLS_BLE module documentation
**  @{
*/         


#ifndef __CLS_BLE_H
#define __CLS_BLE_H

/* MODULE CLS_BLE. */
#include "MCUC1.h" /* SDK and API used */
#include "CLS_BLEconfig.h" /* configuration */


#ifndef __BWUserType_CLS_BLE_StdIO_OutErr_FctType
#define __BWUserType_CLS_BLE_StdIO_OutErr_FctType
  typedef void (*CLS_BLE_StdIO_OutErr_FctType)(uint8_t); /* Callback for an output or error I/O function */
#endif
#ifndef __BWUserType_CLS_BLE_StdIO_In_FctType
#define __BWUserType_CLS_BLE_StdIO_In_FctType
  typedef void (*CLS_BLE_StdIO_In_FctType)(uint8_t *); /* Callback for an I/O input function. */
#endif
#ifndef __BWUserType_CLS_BLE_StdIO_KeyPressed_FctType
#define __BWUserType_CLS_BLE_StdIO_KeyPressed_FctType
  typedef bool (*CLS_BLE_StdIO_KeyPressed_FctType)(void); /* Callback which returns true if a key has been pressed */
#endif
#ifndef __BWUserType_CLS_BLE_StdIOType
#define __BWUserType_CLS_BLE_StdIOType
  typedef struct {                     /* Record containing input, output and error callback (stdin, stdout, stderr). */
    CLS_BLE_StdIO_In_FctType stdIn;    /* standard input */
    CLS_BLE_StdIO_OutErr_FctType stdOut; /* standard output */
    CLS_BLE_StdIO_OutErr_FctType stdErr; /* standard error */
    CLS_BLE_StdIO_KeyPressed_FctType keyPressed; /* key pressed callback */
  } CLS_BLE_StdIOType;
#endif
#ifndef __BWUserType_CLS_BLE_ConstStdIOType
#define __BWUserType_CLS_BLE_ConstStdIOType
  typedef const CLS_BLE_StdIOType CLS_BLE_ConstStdIOType; /* constant StdIOType */
#endif
#ifndef __BWUserType_CLS_BLE_ParseCommandCallback
#define __BWUserType_CLS_BLE_ParseCommandCallback
  typedef uint8_t (*CLS_BLE_ParseCommandCallback)(const uint8_t *cmd, bool *handled, const CLS_BLE_StdIOType *io); /* Callback for parsing a shell command */
#endif
#ifndef __BWUserType_CLS_BLE_ConstStdIOTypePtr
#define __BWUserType_CLS_BLE_ConstStdIOTypePtr
  typedef const CLS_BLE_ConstStdIOType *CLS_BLE_ConstStdIOTypePtr; /* Pointer to constant standard I/O descriptor */
#endif
#ifndef __BWUserType_CLS_BLE_ConstParseCommandCallback
#define __BWUserType_CLS_BLE_ConstParseCommandCallback
  typedef const CLS_BLE_ParseCommandCallback CLS_BLE_ConstParseCommandCallback; /* Callback for parsing a shell command */
#endif

#define CLS_BLE_DEFAULT_SHELL_BUFFER_SIZE  CLS_BLE_CONFIG_DEFAULT_SHELL_BUFFER_SIZE  /* default buffer size for shell command parsing */

/* Include inherited components */
#include "WAIT1.h"
#include "MCUC1.h"
#include "AS_BLE.h"
#include "UTIL1.h"
#include "XF1.h"
#include "CS1.h"

/* other includes needed */
#include <stddef.h> /* for size_t */

/* settings for command line history */
#define CLS_BLE_HISTORY_ENABLED  0     /* 1: enabled, 0: disabled */
#define CLS_BLE_NOF_HISTORY      0     /* number of items in history */
#define CLS_BLE_HIST_LEN         0     /* history buffer size */

/* settings for silent prefix char */
#define CLS_BLE_SILENT_PREFIX_CHAR    '#' /* with this char as first character in the cmd, printing is silent. Use a space to disable it */
#define CLS_BLE_NO_SILENT_PREFIX_CHAR ' ' /* used for no silent prefix char */
#define CLS_BLE_SILENT_PREFIX_CHAR_ENABLED (CLS_BLE_SILENT_PREFIX_CHAR != CLS_BLE_NO_SILENT_PREFIX_CHAR)

/* multi command support */
#define CLS_BLE_MULTI_CMD_ENABLED   0 /* 1: enabled, 0: disabled */
#define CLS_BLE_MULTI_CMD_SIZE      0 /* max size of each command */
#define CLS_BLE_MULTI_CMD_CHAR      ';' /* separation character */

/* settings for local echo */
#define CLS_BLE_ECHO_ENABLED  0        /* 1: enabled, 0: disabled */

#define CLS_BLE_DEFAULT_SERIAL  CLS_BLE_CONFIG_DEFAULT_SERIAL /* If set to 1, then the shell implements its own StdIO which is returned by CLS_BLE_GetStdio(); */

extern uint8_t CLS_BLE_DefaultShellBuffer[CLS_BLE_DEFAULT_SHELL_BUFFER_SIZE]; /* default buffer which can be used by the application */

#if CLS_BLE_DEFAULT_SERIAL
  extern CLS_BLE_ConstStdIOType CLS_BLE_stdio; /* default standard I/O */
#endif

#define CLS_BLE_DASH_LINE "--------------------------------------------------------------"
/* predefined commands */
#define CLS_BLE_CMD_HELP   "help"
#define CLS_BLE_CMD_STATUS "status"

#ifdef __cplusplus
extern "C" {
#endif

void CLS_BLE_SendStr(const uint8_t *str, CLS_BLE_StdIO_OutErr_FctType io);
/*
** ===================================================================
**     Method      :  CLS_BLE_SendStr (component Shell)
**     Description :
**         Prints a string using an I/O function
**     Parameters  :
**         NAME            - DESCRIPTION
**       * str             - Pointer to string (zero terminated) to be
**                           printed.
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/

uint8_t CLS_BLE_ParseCommand(const uint8_t *cmd, bool *handled, CLS_BLE_ConstStdIOType *io);
/*
** ===================================================================
**     Method      :  CLS_BLE_ParseCommand (component Shell)
**     Description :
**         Parses a shell command. Use 'help' to get a list of
**         supported commands.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * cmd             - Pointer to command string
**       * handled         - Pointer to variable to indicate if
**                           the command has been handled. The caller
**                           passes this variable to the command scanner
**                           to find out if the passed command has been
**                           handled. The variable is initialized by the
**                           caller.
**       * io              - Pointer to I/O callbacks
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

void CLS_BLE_SendNum32s(int32_t val, CLS_BLE_StdIO_OutErr_FctType io);
/*
** ===================================================================
**     Method      :  CLS_BLE_SendNum32s (component Shell)
**     Description :
**         Sends a 32bit signed number to the given I/O
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - number to print
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/

void CLS_BLE_SendNum16s(int16_t val, CLS_BLE_StdIO_OutErr_FctType io);
/*
** ===================================================================
**     Method      :  CLS_BLE_SendNum16s (component Shell)
**     Description :
**         Sends a 16bit signed number to the given I/O
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - number to print
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/

void CLS_BLE_PrintPrompt(CLS_BLE_ConstStdIOType *io);
/*
** ===================================================================
**     Method      :  CLS_BLE_PrintPrompt (component Shell)
**     Description :
**         Prints the prompt to the stdOut channel
**     Parameters  :
**         NAME            - DESCRIPTION
**       * io              - Pointer to IO to be used
**     Returns     : Nothing
** ===================================================================
*/

bool CLS_BLE_ReadLine(uint8_t *bufStart, uint8_t *buf, size_t bufSize, CLS_BLE_ConstStdIOType *io);
/*
** ===================================================================
**     Method      :  CLS_BLE_ReadLine (component Shell)
**     Description :
**         Reads a line from stdIn and returns TRUE if we have a line,
**         FALSE otherwise.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * bufStart        - Pointer to start of buffer
**       * buf             - Pointer to buffer where to read in the
**                           information
**         bufSize         - size of buffer
**       * io              - Pointer to I/O callbacks
**     Returns     :
**         ---             - TRUE if something has been read, FALSE
**                           otherwise
** ===================================================================
*/

uint8_t CLS_BLE_PrintStatus(CLS_BLE_ConstStdIOType *io);
/*
** ===================================================================
**     Method      :  CLS_BLE_PrintStatus (component Shell)
**     Description :
**         Prints various available system status information
**     Parameters  :
**         NAME            - DESCRIPTION
**       * io              - Pointer to I/O callbacks
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

void CLS_BLE_PrintCommandFailed(const uint8_t *cmd, CLS_BLE_ConstStdIOType *io);
/*
** ===================================================================
**     Method      :  CLS_BLE_PrintCommandFailed (component Shell)
**     Description :
**         Prints a standard message for failed or unknown commands
**     Parameters  :
**         NAME            - DESCRIPTION
**       * cmd             - Pointer to command which was failing
**       * io              - Pointer to I/O callbacks
**     Returns     : Nothing
** ===================================================================
*/

uint8_t CLS_BLE_ParseWithCommandTable(const uint8_t *cmd, CLS_BLE_ConstStdIOType *io, CLS_BLE_ConstParseCommandCallback *parseCallback);
/*
** ===================================================================
**     Method      :  CLS_BLE_ParseWithCommandTable (component Shell)
**     Description :
**         Parses a shell command. It handles first the internal
**         commands and will call the provided callback.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * cmd             - Pointer to command string
**       * io              - Pointer to I/O callbacks
**       * parseCallback   - Pointer to callback
**                           which will be called to parse commands in
**                           the user application, or NULL if not used.
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

CLS_BLE_ConstStdIOTypePtr CLS_BLE_GetStdio(void);
/*
** ===================================================================
**     Method      :  CLS_BLE_GetStdio (component Shell)
**     Description :
**         Returns the default stdio channel. This method is only
**         available if a shell is enabled in the component properties.
**     Parameters  : None
**     Returns     :
**         ---             - Pointer to the stdio descriptor
** ===================================================================
*/

void CLS_BLE_SendNum32u(uint32_t val, CLS_BLE_StdIO_OutErr_FctType io);
/*
** ===================================================================
**     Method      :  CLS_BLE_SendNum32u (component Shell)
**     Description :
**         Sends a 32bit unsigned number to the given I/O
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - number to print
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/

void CLS_BLE_SendNum16u(uint16_t val, CLS_BLE_StdIO_OutErr_FctType io);
/*
** ===================================================================
**     Method      :  CLS_BLE_SendNum16u (component Shell)
**     Description :
**         Sends a 16bit unsigned number to the given I/O
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - number to print
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/

void CLS_BLE_SendNum8u(uint8_t val, CLS_BLE_StdIO_OutErr_FctType io);
/*
** ===================================================================
**     Method      :  CLS_BLE_SendNum8u (component Shell)
**     Description :
**         Sends an 8bit unsigned number to the given I/O
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - number to print
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/

void CLS_BLE_SendNum8s(int8_t val, CLS_BLE_StdIO_OutErr_FctType io);
/*
** ===================================================================
**     Method      :  CLS_BLE_SendNum8s (component Shell)
**     Description :
**         Sends an 8bit signed number to the given I/O
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - number to print
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/

void CLS_BLE_Init(void);
/*
** ===================================================================
**     Method      :  CLS_BLE_Init (component Shell)
**     Description :
**         Initializes the module, especially creates the mutex
**         semaphore if an RTOS is used.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void CLS_BLE_RequestSerial(void);
/*
** ===================================================================
**     Method      :  CLS_BLE_RequestSerial (component Shell)
**     Description :
**         Used to get mutual access to the shell console. Only has an
**         effect if using an RTOS with semaphore for the console
**         access.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void CLS_BLE_ReleaseSerial(void);
/*
** ===================================================================
**     Method      :  CLS_BLE_ReleaseSerial (component Shell)
**     Description :
**         Used to release mutual access to the shell console. Only has
**         an effect if using an RTOS with semaphore for the console
**         access.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void CLS_BLE_SendHelpStr(const uint8_t *strCmd, const uint8_t *strHelp, CLS_BLE_StdIO_OutErr_FctType io);
/*
** ===================================================================
**     Method      :  CLS_BLE_SendHelpStr (component Shell)
**     Description :
**         Prints a string using an I/O function, formated for the
**         'help' command
**     Parameters  :
**         NAME            - DESCRIPTION
**       * strCmd          - Pointer to string of the command
**       * strHelp         - Pointer to help text string
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/

void CLS_BLE_SendStatusStr(const uint8_t *strItem, const uint8_t *strStatus, CLS_BLE_StdIO_OutErr_FctType io);
/*
** ===================================================================
**     Method      :  CLS_BLE_SendStatusStr (component Shell)
**     Description :
**         Prints a status string using an I/O function, formated for
**         the 'status' command
**     Parameters  :
**         NAME            - DESCRIPTION
**       * strItem         - Pointer to string of the command
**       * strStatus       - Pointer to help text string
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/

void CLS_BLE_ReadChar(uint8_t *c);
/*
** ===================================================================
**     Method      :  CLS_BLE_ReadChar (component Shell)
**     Description :
**         Reads a character (blocking)
**     Parameters  :
**         NAME            - DESCRIPTION
**       * c               - Pointer to character to be used to store the
**                           result
**     Returns     : Nothing
** ===================================================================
*/

void CLS_BLE_SendChar(uint8_t ch);
/*
** ===================================================================
**     Method      :  CLS_BLE_SendChar (component Shell)
**     Description :
**         Sends a character (blocking)
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - character to be sent
**     Returns     : Nothing
** ===================================================================
*/

bool CLS_BLE_KeyPressed(void);
/*
** ===================================================================
**     Method      :  CLS_BLE_KeyPressed (component Shell)
**     Description :
**         Checks if a key has been pressed (a character is present in
**         the input buffer)
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

void CLS_BLE_Deinit(void);
/*
** ===================================================================
**     Method      :  CLS_BLE_Deinit (component Shell)
**     Description :
**         De-Initializes the module, especially frees the mutex
**         semaphore if an RTOS is used.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void* CLS_BLE_GetSemaphore(void);
/*
** ===================================================================
**     Method      :  CLS_BLE_GetSemaphore (component Shell)
**     Description :
**         Return the semaphore of the shell.
**     Parameters  : None
**     Returns     :
**         ---             - semaphore, or NULL if not used or not
**                           allocated.
** ===================================================================
*/

uint8_t CLS_BLE_ReadAndParseWithCommandTable(uint8_t *cmdBuf, size_t cmdBufSize, CLS_BLE_ConstStdIOType *io, CLS_BLE_ConstParseCommandCallback *parseCallback);
/*
** ===================================================================
**     Method      :  CLS_BLE_ReadAndParseWithCommandTable (component Shell)
**     Description :
**         Reads characters from the default input channel and appends
**         it to the buffer. Once a new line has been detected, the
**         line will be parsed using the handlers in the table.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * cmdBuf          - Pointer to buffer provided by the
**                           caller where to store the command to read
**                           in. Characters will be appended, so make
**                           sure string buffer is initialized with a
**                           zero byte at the beginning.
**         cmdBufSize      - Size of buffer
**       * io              - Pointer to I/O channels to be used
**       * parseCallback   - Pointer to callback
**                           table provided by the user application to
**                           parse commands. The table has a NULL
**                           sentinel.
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

uint8_t CLS_BLE_IterateTable(const uint8_t *cmd, bool *handled, CLS_BLE_ConstStdIOType *io, CLS_BLE_ConstParseCommandCallback *parserTable);
/*
** ===================================================================
**     Method      :  CLS_BLE_IterateTable (component Shell)
**     Description :
**         Parses a shell command. It handles first the internal
**         commands and will call the provided callback.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * cmd             - Pointer to command string
**       * handled         - Pointer to boolean which is set to
**                           TRUE if a command parser has handled the
**                           command.
**       * io              - Pointer to I/O callbacks
**       * parserTable     - Pointer to callback which
**                           will be called to parse commands in the
**                           user application, or NULL if not used.
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

uint8_t CLS_BLE_SetStdio(CLS_BLE_ConstStdIOTypePtr stdio);
/*
** ===================================================================
**     Method      :  CLS_BLE_SetStdio (component Shell)
**     Description :
**         Sets an StdIO structure which is returned by GetStdio()
**     Parameters  :
**         NAME            - DESCRIPTION
**         stdio           - New stdio structure to be used.
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

void CLS_BLE_SendData(const uint8_t *data, uint16_t dataSize, CLS_BLE_StdIO_OutErr_FctType io);
/*
** ===================================================================
**     Method      :  CLS_BLE_SendData (component Shell)
**     Description :
**         Sends data using an I/O function. Unlike SendStr(), with
**         this method it is possible to send binary data, including
**         zero bytes.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * data            - Pointer to data to be sent
**         dataSize        - Number of bytes to be sent.
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/

bool CLS_BLE_IsHistoryCharacter(uint8_t ch, uint8_t *cmdBuf, size_t cmdBufIdx, bool *isPrev);
/*
** ===================================================================
**     Method      :  CLS_BLE_IsHistoryCharacter (component Shell)
**     Description :
**         Returns TRUE if character is a history character
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - current command character
**       * cmdBuf          - Pointer to command line buffer read
**                           so far
**         cmdBufIdx       - Index of character into cmdBuf
**       * isPrev          - Pointer to return value, if it is
**                           'previous' history or not
**     Returns     :
**         ---             - TRUE if it is an accepted history character
** ===================================================================
*/

void CLS_BLE_SendCh(uint8_t ch, CLS_BLE_StdIO_OutErr_FctType io);
/*
** ===================================================================
**     Method      :  CLS_BLE_SendCh (component Shell)
**     Description :
**         Prints a character using an I/O function
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - Character to send
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/

unsigned CLS_BLE_printf(const char *fmt, ...);
/*
** ===================================================================
**     Method      :  CLS_BLE_printf (component Shell)
**     Description :
**         Printf() style function using XFormat component, using the
**         shell default I/O handler.
**     Parameters  :
**         NAME            - DESCRIPTION
**         fmt             - printf style format string
**     Returns     :
**         ---             - number of characters written
** ===================================================================
*/

void CLS_BLE_printfPutChar(void *arg, char c);
/*
** ===================================================================
**     Method      :  CLS_BLE_printfPutChar (component Shell)
**
**     Description :
**         Helper routine for printf
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

unsigned CLS_BLE_printfIO(CLS_BLE_ConstStdIOType *io, const char *fmt, ...);
/*
** ===================================================================
**     Method      :  CLS_BLE_printfIO (component Shell)
**     Description :
**         Printf() style function using XFormat component, using a
**         custom I/O handler.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * io              - Pointer to 
**         fmt             - printf style format string
**     Returns     :
**         ---             - number of characters written
** ===================================================================
*/

void CLS_BLE_SendCharFct(uint8_t ch, uint8_t (*fct)(uint8_t ch));
/*
** ===================================================================
**     Method      :  CLS_BLE_SendCharFct (component Shell)
**     Description :
**         Method to send a character using a standard I/O handle.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - character to be sent
**       * fct             - Function pointer to output function: takes
**                           a byte to write and returns error code.
**     Returns     : Nothing
** ===================================================================
*/

uint8_t CLS_BLE_PrintMemory(void *hndl, uint32_t startAddr, uint32_t endAddr, uint8_t addrSize, uint8_t bytesPerLine, uint8_t (*readfp)(void *, uint32_t, uint8_t*, size_t), CLS_BLE_ConstStdIOType *io);
/*
** ===================================================================
**     Method      :  CLS_BLE_PrintMemory (component Shell)
**     Description :
**         Prints a chunk of memory bytes in a formatted way.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * hndl            - Pointer to 
**         startAddr       - Memory start address
**         endAddr         - Memory end address
**         addrSize        - Number of bytes for the address
**                           (1, 2, 3 or 4)
**         bytesPerLine    - Number of bytes per line
**         readfp          - Function pointer to read the memory.
**                           Returns error code, uses a device handle,
**                           32bit address with a pointer to a buffer
**                           and a buffer size.
**       * io              - Pointer to I/O to be used
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

/* END CLS_BLE. */

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif
/* ifndef __CLS_BLE_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
