/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : CLS_BLE.c
**     Project     : MCCAR_V_2_75
**     Processor   : MK24FN1M0VDC12
**     Component   : Shell
**     Version     : Component 01.106, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-10-01, 16:31, # CodeGen: 192
**     Abstract    :
**         Module implementing a command line shell.
**     Settings    :
**          Component name                                 : CLS_BLE
**          Echo                                           : no
**          Prompt                                         : "CMD> "
**          Project Name                                   : My Project Name
**          Silent Mode Prefix                             : #
**          Buffer Size                                    : 48
**          Blocking Send                                  : Enabled
**            Wait                                         : WAIT1
**            Timeout (ms)                                 : 20
**            Wait Time (ms)                               : 5
**            RTOS Wait                                    : no
**          Status Colon Pos                               : 13
**          Help Semicolon Pos                             : 26
**          Multi Command                                  : Disabled
**          History                                        : no
**          Mutex                                          : no
**          SDK                                            : MCUC1
**          Default Serial                                 : Enabled
**            Console Interface                            : AS_BLE
**          Utility                                        : UTIL1
**          XFormat                                        : XF1
**          Critical Section                               : CS1
**     Contents    :
**         PrintPrompt                  - void CLS_BLE_PrintPrompt(CLS_BLE_ConstStdIOType *io);
**         SendNum8u                    - void CLS_BLE_SendNum8u(uint8_t val, CLS_BLE_StdIO_OutErr_FctType io);
**         SendNum8s                    - void CLS_BLE_SendNum8s(int8_t val, CLS_BLE_StdIO_OutErr_FctType io);
**         SendNum16u                   - void CLS_BLE_SendNum16u(uint16_t val, CLS_BLE_StdIO_OutErr_FctType io);
**         SendNum16s                   - void CLS_BLE_SendNum16s(int16_t val, CLS_BLE_StdIO_OutErr_FctType io);
**         SendNum32u                   - void CLS_BLE_SendNum32u(uint32_t val, CLS_BLE_StdIO_OutErr_FctType io);
**         SendNum32s                   - void CLS_BLE_SendNum32s(int32_t val, CLS_BLE_StdIO_OutErr_FctType io);
**         SendCh                       - void CLS_BLE_SendCh(uint8_t ch, CLS_BLE_StdIO_OutErr_FctType io);
**         SendStr                      - void CLS_BLE_SendStr(const uint8_t *str, CLS_BLE_StdIO_OutErr_FctType io);
**         PrintMemory                  - uint8_t CLS_BLE_PrintMemory(void *hndl, uint32_t startAddr, uint32_t endAddr,...
**         printfIO                     - unsigned CLS_BLE_printfIO(CLS_BLE_ConstStdIOType *io, const char *fmt, ...);
**         printf                       - unsigned CLS_BLE_printf(const char *fmt, ...);
**         SendData                     - void CLS_BLE_SendData(const uint8_t *data, uint16_t dataSize,...
**         PrintStatus                  - uint8_t CLS_BLE_PrintStatus(CLS_BLE_ConstStdIOType *io);
**         ParseCommand                 - uint8_t CLS_BLE_ParseCommand(const uint8_t *cmd, bool *handled,...
**         IsHistoryCharacter           - bool CLS_BLE_IsHistoryCharacter(uint8_t ch, uint8_t *cmdBuf, size_t...
**         ReadLine                     - bool CLS_BLE_ReadLine(uint8_t *bufStart, uint8_t *buf, size_t bufSize,...
**         PrintCommandFailed           - void CLS_BLE_PrintCommandFailed(const uint8_t *cmd, CLS_BLE_ConstStdIOType *io);
**         IterateTable                 - uint8_t CLS_BLE_IterateTable(const uint8_t *cmd, bool *handled,...
**         SetStdio                     - uint8_t CLS_BLE_SetStdio(CLS_BLE_ConstStdIOTypePtr stdio);
**         GetStdio                     - CLS_BLE_ConstStdIOTypePtr CLS_BLE_GetStdio(void);
**         RequestSerial                - void CLS_BLE_RequestSerial(void);
**         ReleaseSerial                - void CLS_BLE_ReleaseSerial(void);
**         ReadAndParseWithCommandTable - uint8_t CLS_BLE_ReadAndParseWithCommandTable(uint8_t *cmdBuf, size_t...
**         ParseWithCommandTable        - uint8_t CLS_BLE_ParseWithCommandTable(const uint8_t *cmd,...
**         GetSemaphore                 - void* CLS_BLE_GetSemaphore(void);
**         SendStatusStr                - void CLS_BLE_SendStatusStr(const uint8_t *strItem, const uint8_t *strStatus,...
**         SendHelpStr                  - void CLS_BLE_SendHelpStr(const uint8_t *strCmd, const uint8_t *strHelp,...
**         ReadChar                     - void CLS_BLE_ReadChar(uint8_t *c);
**         SendChar                     - void CLS_BLE_SendChar(uint8_t ch);
**         KeyPressed                   - bool CLS_BLE_KeyPressed(void);
**         SendCharFct                  - void CLS_BLE_SendCharFct(uint8_t ch, uint8_t (*fct)(uint8_t ch));
**         Init                         - void CLS_BLE_Init(void);
**         Deinit                       - void CLS_BLE_Deinit(void);
**
**     * Copyright (c) 2014-2019, Erich Styger
**      * Web:         https://mcuoneclipse.com
**      * SourceForge: https://sourceforge.net/projects/mcuoneclipse
**      * Git:         https://github.com/ErichStyger/McuOnEclipse_PEx
**      * All rights reserved.
**      *
**      * Redistribution and use in source and binary forms, with or without modification,
**      * are permitted provided that the following conditions are met:
**      *
**      * - Redistributions of source code must retain the above copyright notice, this list
**      *   of conditions and the following disclaimer.
**      *
**      * - Redistributions in binary form must reproduce the above copyright notice, this
**      *   list of conditions and the following disclaimer in the documentation and/or
**      *   other materials provided with the distribution.
**      *
**      * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**      * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**      * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**      * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**      * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**      * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**      * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**      * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**      * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**      * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file CLS_BLE.c
** @version 01.00
** @brief
**         Module implementing a command line shell.
*/         
/*!
**  @addtogroup CLS_BLE_module CLS_BLE module documentation
**  @{
*/         

/* MODULE CLS_BLE. */
#include <ctype.h> /* for isalnum*/

#include "CLS_BLE.h"

uint8_t CLS_BLE_DefaultShellBuffer[CLS_BLE_DEFAULT_SHELL_BUFFER_SIZE]; /* default buffer which can be used by the application */
#if CLS_BLE_HISTORY_ENABLED
  static uint8_t CLS_BLE_history[CLS_BLE_NOF_HISTORY][CLS_BLE_HIST_LEN]; /* History buffers */
  static uint8_t CLS_BLE_history_index = 0; /* Selected command */
#endif
#if CLS_BLE_ECHO_ENABLED
  static bool CLS_BLE_EchoEnabled = TRUE;
#endif

#if CLS_BLE_CONFIG_USE_MUTEX
  #include "FreeRTOS.h"
  #include "task.h"
  #include "semphr.h"
#endif

#ifdef __HC08__
  #pragma MESSAGE DISABLE C3303 /* implicit concatenation of strings */
#endif
#if CLS_BLE_CONFIG_USE_MUTEX
  static SemaphoreHandle_t ShellSem = NULL; /* Semaphore to protect shell SCI access */
#endif

#if CLS_BLE_DEFAULT_SERIAL
  CLS_BLE_ConstStdIOType CLS_BLE_stdio =
  {
    (CLS_BLE_StdIO_In_FctType)CLS_BLE_ReadChar, /* stdin */
    (CLS_BLE_StdIO_OutErr_FctType)CLS_BLE_SendChar, /* stdout */
    (CLS_BLE_StdIO_OutErr_FctType)CLS_BLE_SendChar, /* stderr */
    CLS_BLE_KeyPressed /* if input is not empty */
  };
  static CLS_BLE_ConstStdIOType *CLS_BLE_currStdIO = &CLS_BLE_stdio;
#else
  static CLS_BLE_ConstStdIOType *CLS_BLE_currStdIO = NULL; /* needs to be set through CLS_BLE_SetStdio(); */
#endif
/* Internal method prototypes */
static void SendSeparatedStrings(const uint8_t *strA, const uint8_t *strB, uint8_t tabChar, uint8_t tabPos, CLS_BLE_StdIO_OutErr_FctType io);

/*
** ===================================================================
**     Method      :  CLS_BLE_SendCh (component Shell)
**     Description :
**         Prints a character using an I/O function
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - Character to send
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_SendCh(uint8_t ch, CLS_BLE_StdIO_OutErr_FctType io)
{
  if (io==NULL) {
    return;
  }
  io(ch);
}

/*
** ===================================================================
**     Method      :  CLS_BLE_SendStr (component Shell)
**     Description :
**         Prints a string using an I/O function
**     Parameters  :
**         NAME            - DESCRIPTION
**       * str             - Pointer to string (zero terminated) to be
**                           printed.
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/
/*!
 * \brief Prints a string using I/O callbacks
 * \param[in] str String (zero terminated) to be printed
 * \param[in] io I/O function to be used for printing
 */
void CLS_BLE_SendStr(const uint8_t *str, CLS_BLE_StdIO_OutErr_FctType io)
{
  if (io==NULL) {
    return;
  }
  while(*str!='\0') {
    io(*str++);
  }
}

/*
** ===================================================================
**     Method      :  CLS_BLE_SendNum32s (component Shell)
**     Description :
**         Sends a 32bit signed number to the given I/O
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - number to print
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_SendNum32s(int32_t val, CLS_BLE_StdIO_OutErr_FctType io)
{
  unsigned char buf[sizeof("-1234567890")];

  UTIL1_Num32sToStr(buf, sizeof(buf), val);
  CLS_BLE_SendStr(buf, io);
}

/*
** ===================================================================
**     Method      :  CLS_BLE_SendNum32u (component Shell)
**     Description :
**         Sends a 32bit unsigned number to the given I/O
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - number to print
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_SendNum32u(uint32_t val, CLS_BLE_StdIO_OutErr_FctType io)
{
  unsigned char buf[sizeof("1234567890")];

  UTIL1_Num32uToStr(buf, sizeof(buf), val);
  CLS_BLE_SendStr(buf, io);
}

/*
** ===================================================================
**     Method      :  CLS_BLE_SendNum16s (component Shell)
**     Description :
**         Sends a 16bit signed number to the given I/O
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - number to print
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_SendNum16s(int16_t val, CLS_BLE_StdIO_OutErr_FctType io)
{
  unsigned char buf[sizeof("-12345")];

  UTIL1_Num16sToStr(buf, sizeof(buf), val);
  CLS_BLE_SendStr(buf, io);
}

/*
** ===================================================================
**     Method      :  CLS_BLE_SendNum16u (component Shell)
**     Description :
**         Sends a 16bit unsigned number to the given I/O
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - number to print
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_SendNum16u(uint16_t val, CLS_BLE_StdIO_OutErr_FctType io)
{
  unsigned char buf[sizeof("12345")];

  UTIL1_Num16uToStr(buf, sizeof(buf), val);
  CLS_BLE_SendStr(buf, io);
}

/*
** ===================================================================
**     Method      :  CLS_BLE_SendNum8u (component Shell)
**     Description :
**         Sends an 8bit unsigned number to the given I/O
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - number to print
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_SendNum8u(uint8_t val, CLS_BLE_StdIO_OutErr_FctType io)
{
  unsigned char buf[sizeof("123")];

  UTIL1_Num8uToStr(buf, sizeof(buf), val);
  CLS_BLE_SendStr(buf, io);
}

/*
** ===================================================================
**     Method      :  CLS_BLE_SendNum8s (component Shell)
**     Description :
**         Sends an 8bit signed number to the given I/O
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - number to print
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_SendNum8s(int8_t val, CLS_BLE_StdIO_OutErr_FctType io)
{
  unsigned char buf[sizeof("-123")];

  UTIL1_Num8sToStr(buf, sizeof(buf), val);
  CLS_BLE_SendStr(buf, io);
}

/*
** ===================================================================
**     Method      :  CLS_BLE_ParseCommand (component Shell)
**     Description :
**         Parses a shell command. Use 'help' to get a list of
**         supported commands.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * cmd             - Pointer to command string
**       * handled         - Pointer to variable to indicate if
**                           the command has been handled. The caller
**                           passes this variable to the command scanner
**                           to find out if the passed command has been
**                           handled. The variable is initialized by the
**                           caller.
**       * io              - Pointer to I/O callbacks
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t CLS_BLE_ParseCommand(const uint8_t *cmd, bool *handled, CLS_BLE_ConstStdIOType *io)
{
  if (UTIL1_strcmp((char*)cmd, CLS_BLE_CMD_HELP)==0 || UTIL1_strcmp((char*)cmd, "CLS_BLE help")==0) {
    CLS_BLE_SendStr((unsigned char*)"\r\n", io->stdOut);
    CLS_BLE_SendStr((unsigned char*)CLS_BLE_DASH_LINE, io->stdOut);
    CLS_BLE_SendStr((unsigned char*)"\r\n", io->stdOut);
    CLS_BLE_SendStr((unsigned char*)CLS_BLE_CONFIG_PROJECT_NAME_STRING, io->stdOut);
    CLS_BLE_SendStr((unsigned char*)"\r\n", io->stdOut);
    CLS_BLE_SendStr((unsigned char*)CLS_BLE_DASH_LINE, io->stdOut);
    CLS_BLE_SendStr((unsigned char*)"\r\n", io->stdOut);
    CLS_BLE_SendHelpStr((unsigned char*)"CLS_BLE", (const unsigned char*)"Group of CLS_BLE commands\r\n", io->stdOut);
    CLS_BLE_SendHelpStr((unsigned char*)"  help|status", (const unsigned char*)"Print help or status information\r\n", io->stdOut);
#if CLS_BLE_ECHO_ENABLED
    CLS_BLE_SendHelpStr((unsigned char*)"  echo (on|off)", (const unsigned char*)"Turn echo on or off\r\n", io->stdOut);
#endif
    *handled = TRUE;
    return ERR_OK;
#if CLS_BLE_ECHO_ENABLED
  } else if ((UTIL1_strcmp((char*)cmd, "CLS_BLE echo on")==0)) {
    *handled = TRUE;
    CLS_BLE_EchoEnabled = TRUE;
    return ERR_OK;
  } else if ((UTIL1_strcmp((char*)cmd, "CLS_BLE echo off")==0)) {
    *handled = TRUE;
    CLS_BLE_EchoEnabled = FALSE;
    return ERR_OK;
#endif
  } else if ((UTIL1_strcmp((char*)cmd, CLS_BLE_CMD_STATUS)==0) || (UTIL1_strcmp((char*)cmd, "CLS_BLE status")==0)) {
    *handled = TRUE;
    return CLS_BLE_PrintStatus(io);
  }
  return ERR_OK; /* no error */
}

/*
** ===================================================================
**     Method      :  CLS_BLE_PrintPrompt (component Shell)
**     Description :
**         Prints the prompt to the stdOut channel
**     Parameters  :
**         NAME            - DESCRIPTION
**       * io              - Pointer to IO to be used
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_PrintPrompt(CLS_BLE_ConstStdIOType *io)
{
  CLS_BLE_SendStr((unsigned char*)"\r\n", io->stdOut); /* ensure that there is a new line */
  CLS_BLE_SendStr((unsigned char*)CLS_BLE_CONFIG_PROMPT_STRING, io->stdOut);
}

/*
** ===================================================================
**     Method      :  CLS_BLE_IsHistoryCharacter (component Shell)
**     Description :
**         Returns TRUE if character is a history character
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - current command character
**       * cmdBuf          - Pointer to command line buffer read
**                           so far
**         cmdBufIdx       - Index of character into cmdBuf
**       * isPrev          - Pointer to return value, if it is
**                           'previous' history or not
**     Returns     :
**         ---             - TRUE if it is an accepted history character
** ===================================================================
*/
bool CLS_BLE_IsHistoryCharacter(uint8_t ch, uint8_t *cmdBuf, size_t cmdBufIdx, bool *isPrev)
{
  *isPrev = FALSE;
#if CLS_BLE_HISTORY_ENABLED
  if (   cmdBufIdx==0 /* first character on command line */
      || (UTIL1_strcmp((const char*)cmdBuf, (const char*)CLS_BLE_history[CLS_BLE_history_index])==0) /* pressing prev/next character on previous history element */
      )
  {
    if (ch==CLS_BLE_HISTORY_PREV_CHAR) {
      *isPrev = TRUE;
      return TRUE;
    } else if (ch==CLS_BLE_HISTORY_NEXT_CHAR) {
      *isPrev = FALSE;
      return TRUE;
    }
  }
#if 0
  if (cmdBufIdx==0 || cmdBufIdx==2) { /* accept only first character or sequence as history sequence */
    if (cmdBufIdx==2 && cmdBuf[0]==0x1b && cmdBuf[1]==0x5b) {
      /* up:    0x27 0x5b 0x41
       * down:  0x27 0x5b 0x42
       * right: 0x27 0x5b 0x43
       * left:  0x27 0x5b 0x44
       */
      if (cmdBuf[2]==0x41 /* up */ || cmdBuf[2]==0x44 /* left */) {
        *isPrev = TRUE;
        return TRUE;
      } else if (cmdBuf[2]==0x42 /* down */ || cmdBuf[2]==0x43 /* right */) {
        *isPrev = FALSE;
        return TRUE;
      }
    }
    /* \todo: handle TAB and SHIFT-TAB */
  }
#endif
#else
  (void)ch; /* not used */
  (void)cmdBuf; /* not used */
  (void)cmdBufIdx; /* not used */
#endif
  return FALSE;
}

/*
** ===================================================================
**     Method      :  CLS_BLE_ReadLine (component Shell)
**     Description :
**         Reads a line from stdIn and returns TRUE if we have a line,
**         FALSE otherwise.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * bufStart        - Pointer to start of buffer
**       * buf             - Pointer to buffer where to read in the
**                           information
**         bufSize         - size of buffer
**       * io              - Pointer to I/O callbacks
**     Returns     :
**         ---             - TRUE if something has been read, FALSE
**                           otherwise
** ===================================================================
*/
bool CLS_BLE_ReadLine(uint8_t *bufStart, uint8_t *buf, size_t bufSize, CLS_BLE_ConstStdIOType *io)
{
  uint8_t c;
  bool isBackwardHistory;

  if (io->keyPressed()) {
    for(;;) {                          /* while not '\r' or '\n' */
      c = '\0';                        /* initialize character */
      io->stdIn(&c);                   /* read character */
      if (c=='\0') { /* nothing in rx buffer? Something is wrong... */
        break; /* get out of loop */
      }
      if (c=='\b' || c=='\177') {      /* check for backspace */
        if (buf > bufStart) {          /* Avoid buffer underflow */
#if CLS_BLE_ECHO_ENABLED
           if (CLS_BLE_EchoEnabled) {
             io->stdOut('\b');         /* delete character on terminal */
             io->stdOut(' ');
             io->stdOut('\b');
           }
#endif
           buf--;                      /* delete last character in buffer */
           *buf = '\0';
           bufSize++;
        }
      } else if (CLS_BLE_IsHistoryCharacter(c, bufStart, (size_t)(buf-bufStart), &isBackwardHistory)) {
#if CLS_BLE_HISTORY_ENABLED
        uint8_t cBuf[3]={'\0','\0','\0'}, cBufIdx = 0;
        bool prevInHistory;
#endif

        while (c!='\0') {              /* empty the rx buffer (escape sequence) */
#if CLS_BLE_HISTORY_ENABLED
           cBuf[cBufIdx] = c;
           cBufIdx++;
           if (cBufIdx==sizeof(cBuf)) {
             cBufIdx = 0; /* ring buffer */
           }
#endif
           c = '\0';                   /* initialize character */
           io->stdIn(&c);              /* read character */
        }
#if CLS_BLE_HISTORY_ENABLED
        /* if not an alphanumeric switch to history  */
        prevInHistory = cBufIdx==0 && cBuf[0]==0x1b && cBuf[1]==0x5b && (cBuf[2]==0x41 /*up*/ || cBuf[2]==0x44 /*left*/);
        /* up:    0x27 0x5b 0x41
         * down:  0x27 0x5b 0x42
         * right: 0x27 0x5b 0x43
         * left:  0x27 0x5b 0x44
         */
        if (prevInHistory) {
          UTIL1_strcpy(bufStart, CLS_BLE_HIST_LEN, CLS_BLE_history[CLS_BLE_history_index]);
          CLS_BLE_history_index++;     /* update the index */
          if (CLS_BLE_history_index==CLS_BLE_NOF_HISTORY) {
            CLS_BLE_history_index = 0;
          }
        } else {
          if (CLS_BLE_history_index==0) {
            CLS_BLE_history_index = (CLS_BLE_NOF_HISTORY-1);
          } else {
            CLS_BLE_history_index--;
          }
          UTIL1_strcpy(bufStart, CLS_BLE_HIST_LEN, CLS_BLE_history[CLS_BLE_history_index]);
        }
        bufSize = bufSize + buf - bufStart - UTIL1_strlen((const char*)bufStart); /* update the buffer */
        buf = bufStart + UTIL1_strlen((const char*)bufStart);
#endif
#if CLS_BLE_ECHO_ENABLED
        if (CLS_BLE_EchoEnabled) {
          CLS_BLE_SendStr((unsigned char*)"\r\n", io->stdOut);
          CLS_BLE_PrintPrompt(io);
          CLS_BLE_SendStr(bufStart, io->stdOut);
        }
#endif
      } else {
#if CLS_BLE_ECHO_ENABLED
        if (CLS_BLE_EchoEnabled) {
          io->stdOut(c);               /* echo character */
        }
#endif
        *buf = (uint8_t)c;             /* append character to the string */
        buf++;
        bufSize--;
        if ((c=='\r') || (c=='\n')) {
#if CLS_BLE_ECHO_ENABLED
          if (CLS_BLE_EchoEnabled) {
            CLS_BLE_SendStr((unsigned char*)"\n", io->stdOut);
          }
#endif
#if CLS_BLE_HISTORY_ENABLED
          if ((bufStart[0] != '\0') && (bufStart[0] != '\r') && (bufStart[0] != '\n')) {
            int i;

            for(i=CLS_BLE_NOF_HISTORY-1; i>0;i--) {
              UTIL1_strcpy(CLS_BLE_history[i], CLS_BLE_HIST_LEN, CLS_BLE_history[i-1]); /* move previous commands */
            }
            CLS_BLE_history_index = 0; /* update the history with the current command */
            UTIL1_strcpy(CLS_BLE_history[0], CLS_BLE_HIST_LEN, bufStart); /* add the current command to the history */
            if (buf-bufStart <= CLS_BLE_HIST_LEN) { /* size check */
              CLS_BLE_history[0][buf-bufStart-1] = '\0';
            } else {
              CLS_BLE_history[0][CLS_BLE_HIST_LEN-1] = '\0';
            }
          }
#endif
          break;
        }
        if (bufSize <= 1) {            /* buffer full */
          break;
        }
      }
    } /* for */
    *buf = '\0';                       /* zero terminate string */
    return TRUE;
  } else {
    return FALSE;
  }
}

/*
** ===================================================================
**     Method      :  CLS_BLE_PrintStatus (component Shell)
**     Description :
**         Prints various available system status information
**     Parameters  :
**         NAME            - DESCRIPTION
**       * io              - Pointer to I/O callbacks
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t CLS_BLE_PrintStatus(CLS_BLE_ConstStdIOType *io)
{
  CLS_BLE_SendStatusStr((const unsigned char*)"CLS_BLE", (const unsigned char*)"\r\n", io->stdOut);
  CLS_BLE_SendStatusStr((const unsigned char*)"  Build", (const unsigned char*)__DATE__, io->stdOut);
  CLS_BLE_SendStr((unsigned char*)" ", io->stdOut);
  CLS_BLE_SendStr((unsigned char*)__TIME__, io->stdOut);
  CLS_BLE_SendStr((unsigned char*)"\r\n", io->stdOut);
#if CLS_BLE_ECHO_ENABLED
  CLS_BLE_SendStatusStr((const unsigned char*)"  echo", CLS_BLE_EchoEnabled?(const unsigned char*)"On\r\n":(const unsigned char*)"Off\r\n", io->stdOut);
#endif
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  CLS_BLE_PrintCommandFailed (component Shell)
**     Description :
**         Prints a standard message for failed or unknown commands
**     Parameters  :
**         NAME            - DESCRIPTION
**       * cmd             - Pointer to command which was failing
**       * io              - Pointer to I/O callbacks
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_PrintCommandFailed(const uint8_t *cmd, CLS_BLE_ConstStdIOType *io)
{
  CLS_BLE_SendStr((unsigned char*)"*** Failed or unknown command: ", io->stdErr);
  CLS_BLE_SendStr(cmd, io->stdErr);
  CLS_BLE_SendStr((unsigned char*)"\r\n", io->stdErr);
  CLS_BLE_SendStr((unsigned char*)"*** Type ", io->stdErr);
  CLS_BLE_SendStr((unsigned char*)CLS_BLE_CMD_HELP, io->stdErr);
  CLS_BLE_SendStr((unsigned char*)" to get a list of available commands\r\n", io->stdErr);
}

/*
** ===================================================================
**     Method      :  CLS_BLE_IterateTable (component Shell)
**     Description :
**         Parses a shell command. It handles first the internal
**         commands and will call the provided callback.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * cmd             - Pointer to command string
**       * handled         - Pointer to boolean which is set to
**                           TRUE if a command parser has handled the
**                           command.
**       * io              - Pointer to I/O callbacks
**       * parserTable     - Pointer to callback which
**                           will be called to parse commands in the
**                           user application, or NULL if not used.
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t CLS_BLE_IterateTable(const uint8_t *cmd, bool *handled, CLS_BLE_ConstStdIOType *io, CLS_BLE_ConstParseCommandCallback *parserTable)
{
  uint8_t res = ERR_OK;

  if (parserTable==NULL) { /* no table??? */
    return ERR_FAILED;
  }
  if (io==NULL) { /* no IO handler??? */
    return ERR_FAILED;
  }
  /* iterate through all parser functions in table */
  while(*parserTable!=NULL) {
    if ((*parserTable)(cmd, handled, io)!=ERR_OK) {
      res = ERR_FAILED;
    }
    parserTable++;
  }
  return res;
}

/*
** ===================================================================
**     Method      :  CLS_BLE_ParseWithCommandTable (component Shell)
**     Description :
**         Parses a shell command. It handles first the internal
**         commands and will call the provided callback.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * cmd             - Pointer to command string
**       * io              - Pointer to I/O callbacks
**       * parseCallback   - Pointer to callback
**                           which will be called to parse commands in
**                           the user application, or NULL if not used.
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t CLS_BLE_ParseWithCommandTable(const uint8_t *cmd, CLS_BLE_ConstStdIOType *io, CLS_BLE_ConstParseCommandCallback *parseCallback)
{
  uint8_t res = ERR_OK;
  bool handled;
#if CLS_BLE_SILENT_PREFIX_CHAR_ENABLED
  bool silent = FALSE;
#endif
#if CLS_BLE_MULTI_CMD_ENABLED
  uint8_t buf[CLS_BLE_MULTI_CMD_SIZE];
  uint8_t i;
  bool parseBuffer, finished;
#endif

  if (io==NULL) { /* no I/O handler? */
    return ERR_FAILED;
  }
  if (*cmd=='\0') { /* empty command */
    return ERR_OK;
  }
#if CLS_BLE_MULTI_CMD_ENABLED
  parseBuffer = FALSE;
  finished = FALSE;
  i = 0;
  for(;;) { /* breaks */
    if (i>sizeof(buf)-2) {
      res = ERR_FAILED;
      break; /* buffer overflow */
    }
    buf[i] = *cmd;
    cmd++; i++;
  #if CLS_BLE_SILENT_PREFIX_CHAR_ENABLED
    if (i==1 && buf[0]==CLS_BLE_SILENT_PREFIX_CHAR) { /* first character is silent character */
      silent |= (bool)(buf[0]==CLS_BLE_SILENT_PREFIX_CHAR);
      buf[0] = *cmd; /* skip silent character */
      cmd++;
    }
  #endif
    if (buf[i-1] == CLS_BLE_MULTI_CMD_CHAR) { /* found separator */
      buf[i-1] = '\0';
      parseBuffer = TRUE;
    } else if (buf[i-1]=='\0') {
      parseBuffer = TRUE;
      finished = TRUE;
    }
    if (parseBuffer) {
      handled = FALSE;
      res = CLS_BLE_IterateTable(buf, &handled, io, parseCallback); /* iterate through all parser functions in table */
      if (!handled || res!=ERR_OK) { /* no handler has handled the command, or error? */
        CLS_BLE_PrintCommandFailed(buf, io);
        res = ERR_FAILED;
      }
      parseBuffer = FALSE;
      i = 0; /* restart */
    }
    if (finished) {
      break; /* get out of loop */
    }
  } /* for */
#else
  #if CLS_BLE_SILENT_PREFIX_CHAR_ENABLED
  silent = (bool)(*cmd==CLS_BLE_SILENT_PREFIX_CHAR);
  if (silent) {
    cmd++; /* skip silent character */
  }
  #endif
  handled = FALSE;
  res = CLS_BLE_IterateTable(cmd, &handled, io, parseCallback); /* iterate through all parser functions in table */
  if (!handled || res!=ERR_OK) { /* no handler has handled the command? */
    CLS_BLE_PrintCommandFailed(cmd, io);
    res = ERR_FAILED;
  }
#endif
#if CLS_BLE_SILENT_PREFIX_CHAR_ENABLED
  if (!silent) {
    CLS_BLE_PrintPrompt(io);
  }
#else
  CLS_BLE_PrintPrompt(io);
#endif
  return res;
}

/*
** ===================================================================
**     Method      :  CLS_BLE_SetStdio (component Shell)
**     Description :
**         Sets an StdIO structure which is returned by GetStdio()
**     Parameters  :
**         NAME            - DESCRIPTION
**         stdio           - New stdio structure to be used.
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t CLS_BLE_SetStdio(CLS_BLE_ConstStdIOTypePtr stdio)
{
  CLS_BLE_currStdIO = stdio;
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  CLS_BLE_GetStdio (component Shell)
**     Description :
**         Returns the default stdio channel. This method is only
**         available if a shell is enabled in the component properties.
**     Parameters  : None
**     Returns     :
**         ---             - Pointer to the stdio descriptor
** ===================================================================
*/
CLS_BLE_ConstStdIOTypePtr CLS_BLE_GetStdio(void)
{
  return CLS_BLE_currStdIO;
}

/*
** ===================================================================
**     Method      :  CLS_BLE_ReadAndParseWithCommandTable (component Shell)
**     Description :
**         Reads characters from the default input channel and appends
**         it to the buffer. Once a new line has been detected, the
**         line will be parsed using the handlers in the table.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * cmdBuf          - Pointer to buffer provided by the
**                           caller where to store the command to read
**                           in. Characters will be appended, so make
**                           sure string buffer is initialized with a
**                           zero byte at the beginning.
**         cmdBufSize      - Size of buffer
**       * io              - Pointer to I/O channels to be used
**       * parseCallback   - Pointer to callback
**                           table provided by the user application to
**                           parse commands. The table has a NULL
**                           sentinel.
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t CLS_BLE_ReadAndParseWithCommandTable(uint8_t *cmdBuf, size_t cmdBufSize, CLS_BLE_ConstStdIOType *io, CLS_BLE_ConstParseCommandCallback *parseCallback)
{
  /* IMPORTANT NOTE: this function *appends* to the buffer, so the buffer needs to be initialized first! */
  uint8_t res = ERR_OK;
  size_t len;

  if (io==NULL) { /* no I/O handler? */
    return ERR_FAILED;
  }
  len = UTIL1_strlen((const char*)cmdBuf);
  if (CLS_BLE_ReadLine(cmdBuf, cmdBuf+len, cmdBufSize-len, io)) {
    len = UTIL1_strlen((const char*)cmdBuf); /* length of buffer string */
    if (len==0) { /* error case */
      return ERR_FAILED;
    } else if (len==1 && (cmdBuf[0]=='\n' || cmdBuf[0]=='\r')) { /* eat preceding newline characters */
      cmdBuf[0] = '\0';
    }
    if (len>=cmdBufSize-1) {           /* buffer overflow? Parse what we have, will be likely return an error */
      (void)CLS_BLE_ParseWithCommandTable(cmdBuf, io, parseCallback);
      cmdBuf[0] = '\0'; /* start again */
      res = ERR_OVERFLOW;
    } else if (cmdBuf[len-1]=='\n' || cmdBuf[len-1]=='\r') { /* line end: parse command */
      cmdBuf[len-1] = '\0';            /* remove line end character for parser */
      res = CLS_BLE_ParseWithCommandTable(cmdBuf, io, parseCallback);
      cmdBuf[0] = '\0';                /* start again */
    } else {
      /* continue to append to buffer */
    }
  }
  return res;
}

/*
** ===================================================================
**     Method      :  CLS_BLE_RequestSerial (component Shell)
**     Description :
**         Used to get mutual access to the shell console. Only has an
**         effect if using an RTOS with semaphore for the console
**         access.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_RequestSerial(void)
{
#if CLS_BLE_CONFIG_USE_MUTEX
  (void)xSemaphoreTakeRecursive(ShellSem, portMAX_DELAY);
#endif
}

/*
** ===================================================================
**     Method      :  CLS_BLE_ReleaseSerial (component Shell)
**     Description :
**         Used to release mutual access to the shell console. Only has
**         an effect if using an RTOS with semaphore for the console
**         access.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_ReleaseSerial(void)
{
#if CLS_BLE_CONFIG_USE_MUTEX
  (void)xSemaphoreGiveRecursive(ShellSem);
#endif
}

/*
** ===================================================================
**     Method      :  CLS_BLE_GetSemaphore (component Shell)
**     Description :
**         Return the semaphore of the shell.
**     Parameters  : None
**     Returns     :
**         ---             - semaphore, or NULL if not used or not
**                           allocated.
** ===================================================================
*/
void* CLS_BLE_GetSemaphore(void)
{
#if CLS_BLE_CONFIG_USE_MUTEX
  return ShellSem;
#else
  return NULL;
#endif
}

/*
** ===================================================================
**     Method      :  SendSeparatedStrings (component Shell)
**
**     Description :
**         Prints a string using an I/O function, formated for the 'help' 
**         command
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void SendSeparatedStrings(const uint8_t *strA, const uint8_t *strB, uint8_t tabChar, uint8_t tabPos, CLS_BLE_StdIO_OutErr_FctType io)
{
  /* write command part */
  if (strA!=NULL) {
    while(*strA!='\0' && tabPos>0) {
      io(*strA++);
      tabPos--;
    }
  }
  /* fill up until ';' */
  while(tabPos>0) {
    io(' ');
    tabPos--;
  }
  /* write separator */
  io(tabChar);
  io(' ');
  if (strB!=NULL) {
    /* write help text */
    CLS_BLE_SendStr(strB, io);
  }
}

/*
** ===================================================================
**     Method      :  CLS_BLE_SendHelpStr (component Shell)
**     Description :
**         Prints a string using an I/O function, formated for the
**         'help' command
**     Parameters  :
**         NAME            - DESCRIPTION
**       * strCmd          - Pointer to string of the command
**       * strHelp         - Pointer to help text string
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_SendHelpStr(const uint8_t *strCmd, const uint8_t *strHelp, CLS_BLE_StdIO_OutErr_FctType io)
{
  #define HELP_SEMICOLON_POS  26 /* position of the ';' after the command string */
  SendSeparatedStrings(strCmd, strHelp, ';', HELP_SEMICOLON_POS, io);
}

/*
** ===================================================================
**     Method      :  CLS_BLE_SendStatusStr (component Shell)
**     Description :
**         Prints a status string using an I/O function, formated for
**         the 'status' command
**     Parameters  :
**         NAME            - DESCRIPTION
**       * strItem         - Pointer to string of the command
**       * strStatus       - Pointer to help text string
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_SendStatusStr(const uint8_t *strItem, const uint8_t *strStatus, CLS_BLE_StdIO_OutErr_FctType io)
{
  #define STATUS_COLON_POS  13 /* position of the ':' after the item string */
  SendSeparatedStrings(strItem, strStatus, ':', STATUS_COLON_POS, io);
}

/*
** ===================================================================
**     Method      :  CLS_BLE_ReadChar (component Shell)
**     Description :
**         Reads a character (blocking)
**     Parameters  :
**         NAME            - DESCRIPTION
**       * c               - Pointer to character to be used to store the
**                           result
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_ReadChar(uint8_t *c)
{
#if CLS_BLE_CONFIG_DEFAULT_SERIAL
  uint8_t res;

#if CLS_BLE_CONFIG_USE_MUTEX
  (void)xSemaphoreTakeRecursive(ShellSem, portMAX_DELAY);
#endif
  res = CLS_BLE_CONFIG_DEFAULT_SERIAL_RECEIVE_FCT_NAME((uint8_t*)c);
  if (res==ERR_RXEMPTY) {
    /* no character in buffer */
    *c = '\0';
  }
#if CLS_BLE_CONFIG_USE_MUTEX
  (void)xSemaphoreGiveRecursive(ShellSem);
#endif
#else
  *c = '\0';
  return; /* no serial component set up in properties */
#endif
}

/*
** ===================================================================
**     Method      :  CLS_BLE_SendChar (component Shell)
**     Description :
**         Sends a character (blocking)
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - character to be sent
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_SendChar(uint8_t ch)
{
#if CLS_BLE_CONFIG_DEFAULT_SERIAL
  CLS_BLE_SendCharFct(ch, CLS_BLE_CONFIG_DEFAULT_SERIAL_SEND_FCT_NAME);
#else
  (void)ch;                            /* avoid compiler warning about unused argument */
#endif
}

/*
** ===================================================================
**     Method      :  CLS_BLE_KeyPressed (component Shell)
**     Description :
**         Checks if a key has been pressed (a character is present in
**         the input buffer)
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
bool CLS_BLE_KeyPressed(void)
{
#if CLS_BLE_CONFIG_DEFAULT_SERIAL
  bool res;

#if CLS_BLE_CONFIG_USE_MUTEX
  (void)xSemaphoreTakeRecursive(ShellSem, portMAX_DELAY);
#endif
#if CLS_BLE_CONFIG_DEFAULT_SERIAL
  res = (bool)((CLS_BLE_CONFIG_DEFAULT_SERIAL_RXAVAIL_FCT_NAME()==0U) ? FALSE : TRUE); /* true if there are characters in receive buffer */
#endif
#if CLS_BLE_CONFIG_USE_MUTEX
  (void)xSemaphoreGiveRecursive(ShellSem);
#endif
  return res;
#else
  return FALSE; /* no serial component set up in properties */
#endif
}

/*
** ===================================================================
**     Method      :  CLS_BLE_Init (component Shell)
**     Description :
**         Initializes the module, especially creates the mutex
**         semaphore if an RTOS is used.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_Init(void)
{
#if CLS_BLE_CONFIG_USE_MUTEX
#if configSUPPORT_STATIC_ALLOCATION
  static StaticSemaphore_t xMutexBuffer;
#endif
  bool schedulerStarted;
  CS1_CriticalVariable();

  schedulerStarted = (bool)(xTaskGetSchedulerState()!=taskSCHEDULER_NOT_STARTED);
  if (!schedulerStarted) { /* FreeRTOS not started yet. We are called in PE_low_level_init(), and interrupts are disabled */
    CS1_EnterCritical();
  }
#if configSUPPORT_STATIC_ALLOCATION
  ShellSem = xSemaphoreCreateRecursiveMutexStatic(&xMutexBuffer);
#else
  ShellSem = xSemaphoreCreateRecursiveMutex();
#endif
  if (!schedulerStarted) { /* above RTOS call might have enabled interrupts! Make sure we restore the state */
    CS1_ExitCritical();
  }
  if (ShellSem==NULL) { /* semaphore creation failed */
    for(;;) {} /* error, not enough memory? */
  }
  vQueueAddToRegistry(ShellSem, "CLS_BLE_Sem");
#endif
#if CLS_BLE_HISTORY_ENABLED
  {
    int i;

    CLS_BLE_history_index = 0;
    for(i=0; i<CLS_BLE_NOF_HISTORY;i++) {
      CLS_BLE_history[i][0] = '\0';
    }
  }
#endif
#if CLS_BLE_ECHO_ENABLED
  CLS_BLE_EchoEnabled = TRUE;
#endif
}

/*
** ===================================================================
**     Method      :  CLS_BLE_Deinit (component Shell)
**     Description :
**         De-Initializes the module, especially frees the mutex
**         semaphore if an RTOS is used.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_Deinit(void)
{
#if CLS_BLE_CONFIG_USE_MUTEX
  vQueueUnregisterQueue(ShellSem);
  vSemaphoreDelete(ShellSem);
  ShellSem = NULL;
#endif
}

/*
** ===================================================================
**     Method      :  CLS_BLE_SendData (component Shell)
**     Description :
**         Sends data using an I/O function. Unlike SendStr(), with
**         this method it is possible to send binary data, including
**         zero bytes.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * data            - Pointer to data to be sent
**         dataSize        - Number of bytes to be sent.
**         io              - I/O callbacks to be used for printing.
**     Returns     : Nothing
** ===================================================================
*/
/*!
 * \brief Sends data using I/O callbacks
 * \param[in] data Pointer to data to be sent
 * \param[in] io I/O function to be used for sending
 */
void CLS_BLE_SendData(const uint8_t *data, uint16_t dataSize, CLS_BLE_StdIO_OutErr_FctType io)
{
  while(dataSize>0) {
    io(*data++);
    dataSize--;
  }
}

/*
** ===================================================================
**     Method      :  CLS_BLE_printfPutChar (component Shell)
**
**     Description :
**         Helper routine for printf
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void CLS_BLE_printfPutChar(void *arg, char c)
{
  CLS_BLE_StdIO_OutErr_FctType fct = (CLS_BLE_StdIO_OutErr_FctType)arg;

  fct(c); /* print character */
}

/*
** ===================================================================
**     Method      :  CLS_BLE_printfIO (component Shell)
**     Description :
**         Printf() style function using XFormat component, using a
**         custom I/O handler.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * io              - Pointer to 
**         fmt             - printf style format string
**     Returns     :
**         ---             - number of characters written
** ===================================================================
*/
unsigned CLS_BLE_printfIO(CLS_BLE_ConstStdIOType *io, const char *fmt, ...)
{
  va_list args;
  unsigned int count = 0;

  va_start(args,fmt);
  count = XF1_xvformat(CLS_BLE_printfPutChar, (void*)io->stdOut, fmt, args);
  va_end(args);
  return count;
}

/*
** ===================================================================
**     Method      :  CLS_BLE_printf (component Shell)
**     Description :
**         Printf() style function using XFormat component, using the
**         shell default I/O handler.
**     Parameters  :
**         NAME            - DESCRIPTION
**         fmt             - printf style format string
**     Returns     :
**         ---             - number of characters written
** ===================================================================
*/
unsigned CLS_BLE_printf(const char *fmt, ...)
{
  va_list args;
  unsigned int count = 0;

  va_start(args,fmt);
  count = XF1_xvformat(CLS_BLE_printfPutChar, (void*)CLS_BLE_GetStdio()->stdOut, fmt, args);
  va_end(args);
  return count;
}

/*
** ===================================================================
**     Method      :  CLS_BLE_SendCharFct (component Shell)
**     Description :
**         Method to send a character using a standard I/O handle.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - character to be sent
**       * fct             - Function pointer to output function: takes
**                           a byte to write and returns error code.
**     Returns     : Nothing
** ===================================================================
*/
void CLS_BLE_SendCharFct(uint8_t ch, uint8_t (*fct)(uint8_t ch))
{
#if CLS_BLE_CONFIG_BLOCKING_SEND_ENABLED
  uint8_t res;
  #if CLS_BLE_CONFIG_BLOCKING_SEND_TIMEOUT_MS>0
  int timeoutMs = CLS_BLE_CONFIG_BLOCKING_SEND_TIMEOUT_MS;
  #endif
#endif

#if CLS_BLE_CONFIG_USE_MUTEX
  (void)xSemaphoreTakeRecursive(ShellSem, portMAX_DELAY);
#endif
#if CLS_BLE_CONFIG_BLOCKING_SEND_ENABLED
  do {
    res = fct((uint8_t)ch);            /* Send char, returns error code */
  #if CLS_BLE_CONFIG_BLOCKING_SEND_TIMEOUT_MS>0
    if (res==ERR_TXFULL) {
    #if CLS_BLE_CONFIG_BLOCKING_SEND_RTOS_WAIT
      WAIT1_WaitOSms(CLS_BLE_CONFIG_BLOCKING_SEND_TIMEOUT_WAIT_MS);
    #else
      WAIT1_Waitms(CLS_BLE_CONFIG_BLOCKING_SEND_TIMEOUT_WAIT_MS);
    #endif
    }
  #endif
  #if CLS_BLE_CONFIG_BLOCKING_SEND_TIMEOUT_MS>0
    if(timeoutMs<=0) {
      break; /* timeout */
    }
    timeoutMs -= CLS_BLE_CONFIG_BLOCKING_SEND_TIMEOUT_WAIT_MS;
  #endif
  } while(res==ERR_TXFULL);
#else
  (void)fct((uint8_t)ch);              /* non blocking send */
#endif
#if CLS_BLE_CONFIG_USE_MUTEX
  (void)xSemaphoreGiveRecursive(ShellSem);
#endif
}

/*
** ===================================================================
**     Method      :  CLS_BLE_PrintMemory (component Shell)
**     Description :
**         Prints a chunk of memory bytes in a formatted way.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * hndl            - Pointer to 
**         startAddr       - Memory start address
**         endAddr         - Memory end address
**         addrSize        - Number of bytes for the address
**                           (1, 2, 3 or 4)
**         bytesPerLine    - Number of bytes per line
**         readfp          - Function pointer to read the memory.
**                           Returns error code, uses a device handle,
**                           32bit address with a pointer to a buffer
**                           and a buffer size.
**       * io              - Pointer to I/O to be used
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t CLS_BLE_PrintMemory(void *hndl, uint32_t startAddr, uint32_t endAddr, uint8_t addrSize, uint8_t bytesPerLine, uint8_t (*readfp)(void *, uint32_t, uint8_t*, size_t), CLS_BLE_ConstStdIOType *io)
{
  #define NOF_BYTES_PER_LINE 32 /* how many bytes are shown on a line. This defines as well the chunk size we read from memory */
  #define MAX_NOF_BYTES_PER_LINE 32
  uint8_t buf[MAX_NOF_BYTES_PER_LINE]; /* this is the chunk of data we get (per line in output) */
  uint8_t str[3*MAX_NOF_BYTES_PER_LINE+((MAX_NOF_BYTES_PER_LINE+1)/8)+1]; /* maximum string for output:
                                              - '3*' because each byte is 2 hex digits plus a space
                                              - '(NOF_BYTES_PER_LINE+1)/8' because we add a space between every 8 byte block
                                              - '+1' for the final zero byte */
  uint32_t addr;
  uint8_t res=0, j, bufSize;
  uint8_t ch;

  if (endAddr<startAddr) {
    CLS_BLE_SendStr((unsigned char*)"\r\n*** End address must be larger or equal than start address\r\n", io->stdErr);
    return ERR_RANGE;
  }
  for(addr=startAddr; addr<=endAddr; /* nothing */ ) {
    if (endAddr-addr+1 >= bytesPerLine) { /* read only part of buffer */
      bufSize = bytesPerLine; /* read full buffer */
    } else {
      bufSize = (uint8_t)(endAddr-addr+1);
    }
    if (readfp(hndl, addr, buf, bufSize)!=ERR_OK) {
      CLS_BLE_SendStr((unsigned char*)"\r\n*** Read failed!\r\n", io->stdErr);
      return ERR_FAILED;
    }
    if (res != ERR_OK) {
      CLS_BLE_SendStr((unsigned char*)"\r\n*** Failure reading memory block!\r\n", io->stdErr);
      return ERR_FAULT;
    }
    /* write address */
    UTIL1_strcpy(str, sizeof(str), (unsigned char*)"0x");
    UTIL1_strcatNumHex(str, sizeof(str), addr, addrSize);
    UTIL1_chcat(str, sizeof(str), ':');
    CLS_BLE_SendStr((unsigned char*)str, io->stdOut);
    /* write data in hex */
    str[0] = '\0';
    for (j=0; j<bufSize; j++) {
      if ((j)==0) {
        UTIL1_chcat(str, sizeof(str), ' ');
      }
      UTIL1_strcatNum8Hex(str, sizeof(str), buf[j]);
      UTIL1_chcat(str, sizeof(str), ' ');
    }
    for (/*empty*/; j<bytesPerLine; j++) { /* fill up line */
      UTIL1_strcat(str, sizeof(str), (unsigned char*)"-- ");
    }
    CLS_BLE_SendStr((unsigned char*)str, io->stdOut);
    /* write in ASCII */
    io->stdOut(' ');
    for (j=0; j<bufSize; j++) {
      ch = buf[j];
      if (ch >= ' ' && ch <= 0x7f) {
        io->stdOut(ch);
      } else {
        io->stdOut('.'); /* place holder */
      }
    }
    for (/*empty*/; j<bytesPerLine; j++) { /* fill up line */
      UTIL1_strcat(str, sizeof(str), (unsigned char*)"-- ");
    }
    CLS_BLE_SendStr((unsigned char*)"\r\n", io->stdOut);
    addr += bytesPerLine;
  }
  return ERR_OK;
}

/* END CLS_BLE. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
