/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : I_Motor_L.c
**     Project     : MCCAR_V_2_75
**     Processor   : MK24FN1M0VDC12
**     Component   : DAC
**     Version     : Component 01.096, Driver 01.00, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-07-03, 09:33, # CodeGen: 101
**     Abstract    :
**         This component "DAC" implements an internal D/A converter
**         of the MCU. It allows select channels of D/A converter and
**         contains methods for converting various format of a value to
**         supported format of the D/A converter.
**
**     Settings    :
**          Component name                                 : I_Motor_L
**          DAC_LDD                                        : DAC_LDD
**          D/A converter                                  : DAC1
**          D/A channels                                   : 1
**            Channel0                                     : 
**              Channel output pin                         : Enabled
**                D/A channel (pin)                        : DAC1_OUT/CMP0_IN4/CMP2_IN3/ADC1_SE23
**              Init value                                 : 0
**          D/A resolution                                 : 12 bits
**          Data mode                                      : Right justified/unsigned
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**     Contents    :
**         SetValue - byte I_Motor_L_SetValue(void* Values);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file I_Motor_L.c
** @version 01.00
** @brief
**         This component "DAC" implements an internal D/A converter
**         of the MCU. It allows select channels of D/A converter and
**         contains methods for converting various format of a value to
**         supported format of the D/A converter.
**
*/         
/*!
**  @addtogroup I_Motor_L_module I_Motor_L module documentation
**  @{
*/         

/* MODULE I_Motor_L. */

#include "I_Motor_L.h"

#ifdef __cplusplus
extern "C" {
#endif 

/*
** ===================================================================
**     Method      :  I_Motor_L_SetValue (component DAC)
**     Description :
**         This method sets values of all channels.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Values          - Pointer to array that contains the
**                           data. Data type is byte, word or int. It
**                           depends on supported modes, resolution, etc.
**                           of the D/A converter. See version specific
**                           information for the current CPU in <General
**                           Info>.
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK
** ===================================================================
*/
/*
byte I_Motor_L_SetValue(void* Values)
**  This method is implemented as a macro. See I_Motor_L.h file.  **
*/


/* END I_Motor_L. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
