/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : PE_LDD.h
**     Project     : MCCAR_V_2_75
**     Processor   : MK24FN1M0VDC12
**     Version     : Component 01.046, Driver 01.00, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-07-11, 12:24, # CodeGen: 130
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file PE_LDD.h                                                  
** @version 01.00
*/         
/*!
**  @addtogroup PE_LDD_module PE_LDD module documentation
**  @{
*/         
#ifndef __PE_LDD_H
#define __PE_LDD_H

/* MODULE PE_LDD. */

#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "LED_BLUE_F_L.h"
#include "LEDpin1.h"
#include "BitIoLdd1.h"
#include "MCUC1.h"
#include "LED_RED_F_L.h"
#include "LEDpin2.h"
#include "BitIoLdd2.h"
#include "LED_GREEN_F_L.h"
#include "LEDpin3.h"
#include "BitIoLdd3.h"
#include "LED_BLUE_F_R.h"
#include "LEDpin4.h"
#include "BitIoLdd4.h"
#include "LED_RED_F_R.h"
#include "LEDpin5.h"
#include "BitIoLdd5.h"
#include "LED_GREEN_F_R.h"
#include "LEDpin6.h"
#include "BitIoLdd6.h"
#include "WAIT1.h"
#include "GI2C1.h"
#include "CI2C1.h"
#include "JOY_UP.h"
#include "BitIoLdd16.h"
#include "JOY_DOWN.h"
#include "BitIoLdd17.h"
#include "JOY_LEFT.h"
#include "BitIoLdd18.h"
#include "JOY_RIGHT.h"
#include "BitIoLdd19.h"
#include "JOY_PUSH.h"
#include "BitIoLdd20.h"
#include "AS_BLE.h"
#include "ASerialLdd1.h"
#include "CLS_BLE.h"
#include "UTIL1.h"
#include "XF1.h"
#include "CS1.h"
#include "AS_PRG.h"
#include "ASerialLdd2.h"
#include "I_Motor_R.h"
#include "DacLdd1.h"
#include "Kill.h"
#include "BitIoLdd27.h"
#include "PWR_BTN.h"
#include "BitIoLdd28.h"
#include "BLE_Mode.h"
#include "BitIoLdd31.h"
#include "ADC_0.h"
#include "AdcLdd2.h"
#include "TU5.h"
#include "Distance_INT.h"
#include "TimerIntLdd1.h"
#include "TU3.h"
#include "FC1.h"
#include "FreeCntrLdd1.h"
#include "ADC_1.h"
#include "AdcLdd3.h"
#include "DRV1_FAULT.h"
#include "BitIoLdd7.h"
#include "DRV1_EN.h"
#include "BitIoLdd10.h"
#include "DRV1_PH.h"
#include "BitIoLdd8.h"
#include "DRV1_PMODE.h"
#include "BitIoLdd14.h"
#include "I_Motor_L.h"
#include "DacLdd2.h"
#include "DRV2_FAULT.h"
#include "BitIoLdd15.h"
#include "DRV2_EN.h"
#include "BitIoLdd21.h"
#include "DRV2_PH.h"
#include "BitIoLdd22.h"
#include "DRV2_PMODE.h"
#include "BitIoLdd23.h"
#include "IMU_INT.h"
#include "BitIoLdd24.h"
#include "BLE_CONNECTED.h"
#include "BitIoLdd25.h"
#include "PWR_SW.h"
#include "BitIoLdd26.h"
#include "BAT_LOW.h"
#include "BitIoLdd29.h"
#include "CHARGE_STATUS.h"
#include "BitIoLdd30.h"
#include "I_LED_SL.h"
#include "BitIoLdd32.h"
#include "SM1.h"
#include "SMasterLdd1.h"
#include "SLEEP_R.h"
#include "BitIoLdd33.h"
#include "SLEEP_L.h"
#include "BitIoLdd34.h"
#include "Pins1.h"
#include "I_LED_L.h"
#include "BitIoLdd35.h"
#include "I_LED_ML.h"
#include "BitIoLdd36.h"
#include "I_LED_MR.h"
#include "BitIoLdd37.h"
#include "I_LED_R.h"
#include "BitIoLdd38.h"
#include "I_LED_SR.h"
#include "BitIoLdd39.h"
#include "BLE_RST.h"
#include "BitIoLdd40.h"
#include "SYSOFF.h"
#include "BitIoLdd41.h"


/*
** ===================================================================
** Function prototypes
** ===================================================================
*/

/*
** ===================================================================
**     Method      :  Cpu_PE_FillMemory (component MK24FN1M0DC12)
*/
/*!
**     @brief
**         Fills a memory area block by a specified value.
**     @param
**       SourceAddressPtr - Source address pointer.
**     @param
**       c - A value used to fill a memory block.
**     @param
**       len - Length of a memory block to fill.
*/
/* ===================================================================*/
void PE_FillMemory(register void* SourceAddressPtr, register uint8_t c, register uint32_t len);

/*
** ===================================================================
**     Method      :  Cpu_PE_PeripheralUsed (component MK24FN1M0DC12)
*/
/*!
**     @brief
**         Returns information whether a peripheral is allocated by PEx 
**         or not.
**     @param
**       PrphBaseAddress - Base address of a peripheral.
**     @return
**       TRUE if a peripheral is used by PEx or FALSE if it isn't used.
*/
/* ===================================================================*/
bool PE_PeripheralUsed(uint32_t PrphBaseAddress);

/*
** ===================================================================
**     Method      :  Cpu_LDD_SetClockConfiguration (component MK24FN1M0DC12)
*/
/*!
**     @brief
**         Changes the clock configuration of all LDD components in a 
**         project.
**     @param
**       ClockConfiguration - New CPU clock configuration changed by CPU SetClockConfiguration method.
*/
/* ===================================================================*/
void LDD_SetClockConfiguration(LDD_TClockConfiguration ClockConfiguration);

/* END PE_LDD. */


#endif

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
