/*
 * ExploreConfig.h
 *
 *  Created on: 08.11.2019
 *      Author: Theo
 */

#ifndef EXPLORECONFIG_H
#define EXPLORECONFIG_H


#define ENABLE_TIMING_CONROLL
#define ENABLE_DATALOG

#define MAZE_FIELDS_WIDTH_NORTH_DIRECTION (9)
#define MAZE_FIELDS_LENGTH_EAST_DIRECTION (9)

#define MAZE_FIELD_LENGTH (0.17)
#define HALF_OF_MAZE_FIELD_LENGTH (0.85)
#define QUARTER_OF_MAZE_FIELD_LENGTH (0.0425)



#endif
